### ISSUE TITLE
Nix flake build fails in `installPhase`

### ISSUE THREAD

**Issue by phijor** [idris-community/idris2-lsp#212]
Trying to build `idris2-lsp` with the provided Nix flake fails in `installPhase` when attempting to wrap `libidris2_support`:

```console
$ nix build -L
... <snip> ...
idris2-lsp> Running phase: installPhase
idris2-lsp> Builder called die: Cannot wrap '/nix/store/z312y1wi9mv15hfbbbrlk53jc2iq74i7-idris2-lsp/bin/libidris2_support' because it is not an executable file
```

I am not familiar enough with the Idris build process, but it seems like `buildIdris` is failing here:

https://github.com/idris-lang/Idris2/blob/da6f0b0e4e99b398190deca2dfef6bec84f0062c/nix/buildIdris.nix#L39-L41

**Comment by mattpolzin** [comment]
This is unfortunate, and again related to me only having built the LSP on my MacOS device.

Compiling with the Idris2 Scheme backend (default) produces a `.so` file that is actually the executable Scheme loads to run the program. On MacOS, that's the only `.so` file in the `*_app` folder. That is, of course, not the case on Linux platforms where the Idris support library also has a `.so` extension. The right solution may be to exclude the Idris support library explicitly in the `buildIdris` code. we don't want it at all since the support library is built as its own derivation for Nix builds.

**Comment by mattpolzin** [comment]
Here's my proposed fix: https://github.com/idris-lang/Idris2/pull/3195

I won't have time to test it until this evening and I'll be sure to test it on both MacOS and Linux via a VM.

You could pin Idris to that branch I just linked to and then tell this LSP flake to follow that to test this out before it merges if you'd like.

**Comment by mattpolzin** [comment]
Alright, ran through the whole build and execution of the LSP server on both MacOS and Linux this time.

**Comment by phijor** [comment]
Great, thank you! I can confirm that it does build successfully now :)
