### ISSUE TITLE
`PACK_DIR` environment variable being ignored

### ISSUE THREAD

**Issue by foxyseta** [idris-community/idris2-lsp#219]
This command seems to ignore the provided `PACK_DIR` value and install in `.pack/bin` anyway:
```bash
$ PACK_DIR=/home/foxy/desktop/ pack -p nightly-240617 install-app idris2-lsp
```

**Comment by mattpolzin** [comment]
Applications pack installs won’t generally know anything about pack and that is the case with the LSP server. I see you’ve opened this issue against the pack repository as well already so that’s the spot to look out for a definitive answer. 

That said, I’ll take a stab at guessing what’s going on. I’m guessing pack doesn’t support choosing a different PACK_DIR for every command but rather it uses a single configurable directory determined when you install pack.

**Comment by foxyseta** [comment]
You make a good point! Will update my other issue accordingly. Thanks!

**Comment by foxyseta** [comment]
If I may ask, what about the manual installation process? Can it be used for an installation living somewhere other than `~/.idris2/bin`?

**Comment by mattpolzin** [comment]
Yeah; `PREFIX=/some/dir make install` will install the LSP server into `$PREFIX/bin`.

**Comment by foxyseta** [comment]
> Applications pack installs won’t generally know anything about pack and that is the case with the LSP server. I see you’ve opened this issue against the pack repository as well already so that’s the spot to look out for a definitive answer.
> 
> That said, I’ll take a stab at guessing what’s going on. I’m guessing pack doesn’t support choosing a different PACK_DIR for every command but rather it uses a single configurable directory determined when you install pack.

https://github.com/stefan-hoeck/idris2-pack/issues/292#issuecomment-2182204155

> Yeah; PREFIX=/some/dir make install will install the LSP server into $PREFIX/bin.

Thanks! Will give this a try soon. Maybe it could be documented in the README?

**Comment by mattpolzin** [comment]
Yeah, the README mentions that there’s a default install location but not that there’s an easy way to change that — a PR clarifying that in the README would be welcome! Though I’m not signing me or you up for that by saying so.

**Comment by mattpolzin** [comment]
Correct; Idris itself also supports a similar override of install prefix (I think it’s the same PREFIX variable but I’d need to take a look to be sure). There’s a bit more to this all than just installing in a certain spot because the compiler and the LSP both need to be looking in the right place to locate installed packages. That happens automatically if they both get installed at the same prefix. Otherwise, the IDRIS2_PACKAGE_PATH variable needs to be used to tell them to look in additional locations for installed packages.

**Comment by foxyseta** [comment]
Yes, that's called `PREFIX` too, apprently: https://github.com/idris-lang/Idris2/blob/main/INSTALL.md#1-set-installation-target-directory.

The following script correctly installed `idris2` and `idris2-lsp` in a local directory of mine, leaving `~/.idris2/` and `~/.pack/` clean.

```bash
# If you already have idris2, uninstall idris2 unless you installed it from source
DIR=/home/foxy/desktop/test/ # where $DIR/bin/ is assumed to be in your PATH
git clone --recurse-submodules --depth=1 \
  https://github.com/idris-community/idris2-lsp.git # Clone this repository
cd idris2-lsp/Idris2/
make bootstrap SCHEME=chez PREFIX=$DIR # Boostrap Idris
make install PREFIX=$DIR # Install Idris
# If needed, modify your shell files to ensure ~/.idris2/bin is in your PATH
make clean # Clean Idris
make all PREFIX=$DIR # Build Idris
make install PREFIX=$DIR # Install Idris
make install-with-src-libs PREFIX=$DIR # Install sources for libraries
make install-with-src-api PREFIX=$DIR # Install the API with sources
cd ../LSP-lib
idris2 --install-with-src # Install the LSP library
cd .. # Go back to the idris2-lsp directory
make install PREFIX=$DIR # Install idris2-lsp
```

As I am installing both of them at the same prefix, they should look for installed packages in the same place.
