### ISSUE TITLE
Create a nix build

### ISSUE THREAD

**Issue by rambip** [idris-community/idris2-lsp#68]
Idris2 seems to be a really great language, and I would love to get started.
A language server was exactly what I was looking for to get started with dependent type programming.

I don't know anything about scheme, the build process you use and the exact version of the language I need to compile, so it would be really nice if i could install it with nix (like I did with the idris2 compiler)

Is this something you consider doing ?

**Comment by ShinKage** [comment]
Yes, some contributors have started working on distribution, both with "regular" package managers and nix, so it's a when not an if. However I cannot give a timetable since we are few and there is still discussion on how to approach this matter on the compiler side (which the LSP server depends on).

**Comment by xavierzwirtz** [comment]
A bunch of idris2 packages are maintained [here](https://github.com/claymager/idris2-pkgs) including idris2-lsp. I am already using it to install idris2-lsp in my NixOS emacs.

**Comment by michaelmesser** [comment]
Is this still an issue?

**Comment by michaelmesser** [comment]
Reopen if needed
